add instrumentation test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -49,48 +49,52 @@ jobs:
             "**/build/reports"
             "**/build/test-results"
 
-# TODO action consistently fails with "This is because the emulator closed unexpectedly (134)`
-#  connectedAndroidAppTest:
-#    name: Run Android Instrumentation Tests
-#    needs: checkAndUnitTest
-#    runs-on: macos-latest
-#    steps:
-#
-#      - name: Checkout
-#        uses: actions/checkout@v4
-#
-#      - name: Set up JDK
-#        uses: actions/setup-java@v4
-#        with:
-#          distribution: 'zulu'
-#          java-version-file: ./.java-version
-#
-#      - name: Gradle Cache
-#        uses: actions/cache@v4
-#        with:
-#          path: |
-#            ~/.gradle/caches/modules-*
-#            ~/.gradle/caches/jars-*
-#            ~/.gradle/caches/build-cache-*
-#          key: gradle-${{ hashFiles('**/build.gradle*', '**/libs.versions.toml') }}
-#
-#      - name: Gradle Wrapper Cache
-#        uses: actions/cache@v4
-#        with:
-#          path: ~/.gradle/wrapper
-#          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
-#
-#      - name: Accept Android Package Licenses
-#        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true
-#
-#      - name: Run instrumented tests
-#        run: ./gradlew cleanManagedDevices --unused-only &&
-#            ./gradlew -Dorg.gradle.workers.max=1 :app:allDevicesDebugAndroidTest
-#            -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true
-#
-#      - name: Upload test reports
-#        if: ${{ success() || failure() }}
-#        uses: actions/upload-artifact@v4
-#        with:
-#          name: test-reports
-#          path: "**/build/reports/androidTests"
+  # TODO action consistently fails with "This is because the emulator closed unexpectedly (134)`
+  # https://issuetracker.google.com/issues/287312019
+  connectedAndroidAppTest:
+    name: Run Android Instrumentation Tests
+    needs: checkAndUnitTest
+    runs-on: macos-latest
+    steps:
+
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'zulu'
+          java-version-file: ./.java-version
+
+      - name: Gradle Cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.gradle/caches/modules-*
+            ~/.gradle/caches/jars-*
+            ~/.gradle/caches/build-cache-*
+          key: gradle-${{ hashFiles('**/build.gradle*', '**/libs.versions.toml') }}
+
+      - name: Gradle Wrapper Cache
+        uses: actions/cache@v4
+        with:
+          path: ~/.gradle/wrapper
+          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
+
+      - name: Accept Android Package Licenses
+        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true
+
+      - name: Build AndroidTest apps
+        run: ./gradlew :app:packageDebug :app:packageDebugAndroidTest
+
+      - name: Run instrumented tests
+        run: ./gradlew cleanManagedDevices --unused-only &&
+          ./gradlew :app:allDevicesDebugAndroidTest -Dorg.gradle.workers.max=1
+          -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true -Pandroid.experimental.testOptions.managedDevices.maxConcurrentDevices=1 -Pandroid.experimental.testOptions.managedDevices.setupTimeoutMinutes=180
+
+      - name: Upload test reports
+        if: ${{ success() || failure() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-reports
+          path: "**/build/reports/androidTests"
